server:
  port: 10001
  servlet:    context-path: /leaves
spring:  application:    name: leaves  datasource:    url: jdbc:mysql://127.0.0.1:3306/domoment?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
#    url: jdbc:mysql://127.0.0.1:10101/domoment?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: sug_narulejKjdsP*H#A_domt@leafs^2020c
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone:   
  resources:    static-locations:#    - classpath:/META-INF/resources/
    - classpath:/resources/
#    - classpath:/static/nota-zero/dist/
#    - classpath:/public/
############ mybatis ###########
mybatis:  mapper-locations:  - classpath:**/mapper/*pper.xml
#logging:#  config: src/main/resources/logback-spring.xml
log:
  path: log
  